import { readdirSync, writeFileSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";
import { safeReadJson } from "./lib/json.js";

const ROOT = resolve(import.meta.dirname, "..");
const REPOS_DIR = join(ROOT, "repos");
const TURBO_JSON = join(ROOT, "turbo.json");

interface PackageJson {
  name: string;
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
}

function readPackageJson(dir: string): PackageJson | null {
  const pkgPath = join(dir, "package.json");
  if (!existsSync(pkgPath)) return null;
  return safeReadJson<PackageJson>(pkgPath);
}

export function generate(): void {
  if (!existsSync(REPOS_DIR)) {
    console.log("No repos/ directory — skipping turbo graph generation");
    return;
  }

  const repoDirs = readdirSync(REPOS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name);

  const workspacePackageNames = new Set<string>();
  for (const dir of repoDirs) {
    const pkg = readPackageJson(join(REPOS_DIR, dir));
    if (pkg?.name) workspacePackageNames.add(pkg.name);
  }

  const packageDeps = new Map<string, string[]>();

  for (const dir of repoDirs) {
    const pkg = readPackageJson(join(REPOS_DIR, dir));
    if (!pkg?.name) continue;

    const allDeps = {
      ...pkg.dependencies,
      ...pkg.devDependencies,
    };

    const workspaceDeps: string[] = [];
    for (const depName of Object.keys(allDeps)) {
      if (depName !== pkg.name && workspacePackageNames.has(depName)) {
        workspaceDeps.push(depName);
      }
    }

    if (workspaceDeps.length > 0) {
      packageDeps.set(pkg.name, workspaceDeps);
    }
  }

  const turboJson = safeReadJson<
    { tasks: Record<string, unknown>; [key: string]: unknown }
  >(TURBO_JSON);

  for (const key of Object.keys(turboJson.tasks)) {
    if (key.includes("#")) {
      delete turboJson.tasks[key];
    }
  }

  for (const [pkgName, deps] of packageDeps) {
    turboJson.tasks[`${pkgName}#build`] = {
      dependsOn: deps.map((d) => `${d}#build`),
    };
  }

  // Ensure the generated-file warning is the first key
  delete turboJson["//"];
  const output = {
    "//": "Auto-generated by scripts/generate-turbo-graph.ts. Do not edit package-specific entries manually. Run 'just generate-graph' to regenerate.",
    ...turboJson,
  };

  writeFileSync(TURBO_JSON, JSON.stringify(output, null, 2) + "\n");

  const entryCount = packageDeps.size;
  const totalDeps = [...packageDeps.values()].reduce(
    (sum, d) => sum + d.length,
    0,
  );
  console.log(
    `Generated turbo dependency graph: ${entryCount} packages, ${totalDeps} edges`,
  );
  for (const [pkg, deps] of packageDeps) {
    console.log(`  ${pkg} → ${deps.join(", ")}`);
  }
}

generate();
